### ISSUE TITLE
upgrade CRI to v1 from v1alpha2

### ISSUE THREAD

**Issue by SergeyKanzhelev** [containerd/stargz-snapshotter#1005]
k8s 1.26 dropping support for v1alpha2 of CRI https://github.com/kubernetes/kubernetes/pull/110618
. Consider switching the CRI version in snapshotter as well.

**Comment by ktock** [comment]
Thank you for reporting this. Fixed by https://github.com/containerd/stargz-snapshotter/pull/1011.
