### ISSUE TITLE
Is `ctr` supported?

### ISSUE THREAD

**Issue by siscia** [containerd/stargz-snapshotter#110]
Hello guys :)

I am wrapping up our shapshotter plugin for cvmfs now that the support for it is merged in containerd.

I am trying to understand if the `ctr` utility can be used to iteractive testing of the remote snapshotter.
If I simply invoke `ctr plugin list` it shows our own plugin being loaded. Moreover logings seems to show that everything is set up properly.

However, I don't see any kind of activity when I try to `./ctr image pull --snapshotter=cvmfs docker.io/library/redis:4`

Is this expected?

Is there a suggested way to interactively test pluggins?

(Using the 1.4.0-beta release from github.)

Cheers,
Simone

**Comment by ktock** [comment]
Hi! The upstream version of `ctr` doesn't support remote snapshots yet, so you need to write your own.
In our project, we are using our implementation of the subcommand [`rpull`](https://github.com/containerd/stargz-snapshotter/blob/6d3fd7da1e6aa51eeef567fe638cc7b1057d8096/cmd/ctr-remote/commands/rpull.go). 

Based on our `rpull` implementation, you might need to:
- replace [`remoteSnapshotterName` parameter](https://github.com/containerd/stargz-snapshotter/blob/6d3fd7da1e6aa51eeef567fe638cc7b1057d8096/cmd/ctr-remote/commands/rpull.go#L34) to `cvmfs`, and
- modify [handler implementation](https://github.com/containerd/stargz-snapshotter/blob/6d3fd7da1e6aa51eeef567fe638cc7b1057d8096/cmd/ctr-remote/commands/rpull.go#L97) if [labels](https://github.com/containerd/stargz-snapshotter/blob/6d3fd7da1e6aa51eeef567fe638cc7b1057d8096/stargz/handler/handler.go#L28-L31) passed to your `FileSystem` implementation aren't enough.

**Comment by siscia** [comment]
Many thanks!

I was afraid of this, but I wanted to check with you guys!

Cheers,
Simone
