### ISSUE TITLE
How to understand and contribute to this project

### ISSUE THREAD

**Issue by zhiyuanGH** [containerd/stargz-snapshotter#1188]
May I know if there is any guideline for understanding the source code? 
I am interested in this project and want to contribute to it.

**Comment by ktock** [comment]
Thanks for your interest. The followings are some of informations for deeper understanding of stargz snapshotter:

- Docs: https://github.com/containerd/stargz-snapshotter/tree/main/docs
- estargz spec: https://github.com/containerd/stargz-snapshotter/blob/main/docs/estargz.md
- stargz-snapshotter command (`containerd-stargz-grpc`): https://github.com/containerd/stargz-snapshotter/tree/main/cmd/containerd-stargz-grpc
- estargz compressor/decompressor: https://github.com/containerd/stargz-snapshotter/tree/main/estargz

**Comment by zhiyuanGH** [comment]
@ktock 

Thanks for your warm help. I have read the source code but I still have a question. 

From my understanding, after the prioritized Prefetch(), stargz-snapshotter gets the filesystem ready and the container is started. Then there is a non-prioritized aggressive BackgroundFetch() to download the image. 

Before the BackgroundFetch() completes, the image is incomplete. When the container wants to access a missing file, we need to interrupt BackgroundFetch() and fetch the file. 

If my understanding is correct, where does the stargz-snapshotter implement the 'interrupt' to realize on-demand fetching? I think it should be in /fs/fs.go or fs/layer/layer.go but I didn't find it.

Have a nice day.

**Comment by zhiyuanGH** [comment]
@ktock Now I understand the mechanism. It implements interfaces of FUSE to do on-demand fetching. Thank you.
