### ISSUE TITLE
Unable to lazy pull from a private registry

### ISSUE THREAD

**Issue by zhiyuanGH** [containerd/stargz-snapshotter#1247]
I have set up a private registry using Docker registry with the following command:
`nerdctl run -d -p 5000:5000 --restart always --name registry registry:2`

Pulled an example image:
`nerdctl pull ghcr.io/stargz-containers/node:17.8.0-esgz`

Pushed it to my private registry:
`nerdctl tag ghcr.io/stargz-containers/node:17.8.0-esgz localhost:5000/your-image-name`
`nerdctl push localhost:5000/your-image-name`

Try to run it on another server: 
`time nerdctl --snapshotter=stargz run --insecure-registry --rm 158.132.255.210:5000/your-image-name /bin/bash`

However, the log indicates this: 

level":"debug","msg":"checking layer availability","time":"2023-05-22T19:38:14.700953997+08:00"}
level":"debug","mount-point":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/14/fs","msg":"layer is normal snapshot(overlayfs)","time":">
level":"debug","mount-point":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/12/fs","msg":"layer is normal snapshot(overlayfs)","time":">
level":"debug","mount-point":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/11/fs","msg":"layer is normal snapshot(overlayfs)","time":">
level":"debug","mount-point":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/10/fs","msg":"layer is normal snapshot(overlayfs)","time":">
level":"debug","mount-point":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/9/fs","msg":"layer is normal snapshot(overlayfs)","time":"2>
level":"debug","mount-point":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/7/fs","msg":"layer is normal snapshot(overlayfs)","time":"2>
level":"debug","mount-point":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/6/fs","msg":"layer is normal snapshot(overlayfs)","time":"2>
level":"debug","mount-point":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/5/fs","msg":"layer is normal snapshot(overlayfs)","time":"2>
level":"debug","mount-point":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/4/fs","msg":"layer is normal snapshot(overlayfs)","time":"2>
level":"debug","mount-point":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/2/fs","msg":"layer is normal snapshot(overlayfs)","time"

Does it mean that stargz-snapshotter is not running the container in a lazy-pulling way? If so how to fix it? Thank you.

**Comment by zhiyuanGH** [comment]
I think the problem is that my private registry is a HTTP registry rather than a HTTPs registry. So stargz fails to resolve the images. Is there any way to use stargz with HTTP registry?

**Comment by ktock** [comment]
> Is there any way to use stargz with HTTP registry?

https://github.com/containerd/stargz-snapshotter/blob/v0.14.3/docs/overview.md#registry-mirrors-and-insecure-connection

**Comment by zhiyuanGH** [comment]
thanks. it works
