### ISSUE TITLE
optimize image with --stargz-only get an error "digest of TOC JSON must be passed"

### ISSUE THREAD

**Issue by cy-zheng** [containerd/stargz-snapshotter#129]
cmd:
```
ctr-remote image optimize --plain-http --stargz-only golang:1.14.7 {private-registry}/chenyu-test/golang:1.14.7
ctr-remote images rpull --user='{UNAME:PWD}' --plain-http {private-registry}/chenyu-test/golang:1.14.7
```

log output:
```
Aug 17 22:15:45 ava-staging-k8s-stress-test-worker09 containerd-stargz-grpc[2346]: {"error":"digest of TOC JSON must be passed","key":"default/178/extract-707423280-RKQt sha256:943d4a5efe67b44aab74815a110a231c5018e3dac04a4a4f1b9cf826d8000a8e","level":"debug","msg":"failed to prepare remote snapshot","parent":"","remote-snapshot-prepared":"false","time":"2020-08-17T22:15:45.584216442-07:00"}
```

cmd:
```
root@ava-staging-k8s-stress-test-worker09:~# ctr-remote run --rm -t --snapshotter=stargz {private-registry}/chenyu-test/golang:1.14.7 test /bin/bash
root@ava-staging-k8s-stress-test-worker09:/go# cat /.stargz-snapshotter/*
cat: '/.stargz-snapshotter/*': No such file or directory
```

**Comment by ktock** [comment]
Stargz (non-eStargz) image doesn't support [content verification](https://github.com/containerd/stargz-snapshotter/blob/master/docs/verification.md) so the snapshotter doesn't mount it by default.
You need the following configuration for mounting stargz (non-eStargz) layers (see also [the doc](https://github.com/containerd/stargz-snapshotter/blob/master/docs/verification.md#content-verification-in-stargz-snapshotter)).

- set `allow_no_verification = true` in config.toml of stargz snapshotter, and
- specify `--skip-content-verify` to `ctr-remote images rpull` command.

**Comment by AkihiroSuda** [comment]
Is this issue closable? Do we need more clear docs?

**Comment by koxu1996** [comment]
@ktock Is there possibility to use non-eStargz image with KinD? I added `allow_no_verification = true` but I have no clue where is place for `--skip-content-verify` extra argument.

**Comment by ktock** [comment]
@koxu1996 Possible solutions:

- Manually adding `containerd.io/snapshot/remote/stargz.skipverify` to your non-eStargz image.
- Modifying `ctr-remote image optimize` command to always add that annotation to non-eStargz images.
- Adding a knob in config.toml for completely disabling verification feature.
- Adding `--skip-content-verify` like functionality to containerd/cri (not easy).

BTW are there usecase/reason where you want to use non-eStargz image on KinD?

**Comment by koxu1996** [comment]
@ktock I am running cluster with many nodes on single machine and I want avoid copying hundreds gigabytes of images + avoid long pull time. I was using `stargzify` from `google/crfs`, but with recent StarGZ it stopped working - can I assume plain stargz images are useless now? I am also wondering why `allow_no_verification = true` is not enough to disable content verification.

**Comment by ktock** [comment]
@koxu1996 `allow_no_verification` was introduced for allowing to disable verification selectively (mainly for testing stargz images). It'll be good to have a flag for completely disabling verification (option 3 in the above list).
