### ISSUE TITLE
snapshotter (`containerd-stargz-grpc`) should start up with default config when the config file is missing

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/stargz-snapshotter#13]
Currently rsnapshotd doesn't start up when the config file is missing

```
$ sudo ~/gopath/bin/rsnapshotd 
FATA[2020-01-04T20:21:11.540970014+09:00] failed to load config file "/etc/rsnapshotd/config.toml"  error="open /etc/rsnapshotd/config.toml: no such fi
le or directory"
```

**Comment by ktock** [comment]
Thanks for opening it! We can do it since 8a280b2924c18cc06507d3525e194c2e3b57830a 🎉

**Comment by AkihiroSuda** [comment]
This seems got broken again recently on master

**Comment by ohkinozomu** [comment]
I checked https://github.com/containerd/stargz-snapshotter/commit/8a280b2924c18cc06507d3525e194c2e3b57830a , it may be related to my pull request https://github.com/containerd/stargz-snapshotter/pull/214

I may be able to fix that(except for determining the default values), but should It be fixed?
I think the program should exit when there is no config file.
I'm sorry if I lack knowledge about containerd.

**Comment by AkihiroSuda** [comment]
containerd can work without `/etc/containerd/config.toml`.

stargz-snapshotter should work without any config file as well
