### ISSUE TITLE
Allow to disable fetching layers in background

### ISSUE THREAD

**Issue by koxu1996** [containerd/stargz-snapshotter#145]
I have rather specific use case of _StarGZ_: I use it to save disk space, because I am running 64 nodes on my local machine. I don't really care about runtime performance, so fetching layers in background is undesirable behavior for me. Currently I use forked version, but I though maybe such option could be useful for someone else.

I was thinking about adding new config option and wrapping [background fetching](https://github.com/containerd/stargz-snapshotter/blob/master/stargz/fs.go#L324-L356) with something like: `if !fs.nolazypull { ... }`

I could prepare pull request, but would like to introduce such change?

**Comment by ktock** [comment]
SGTM. Can you open a PR?

**Comment by koxu1996** [comment]
Thanks :smiley:
