### ISSUE TITLE
remove dependency on github.com/google/go-containerregistry 

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/stargz-snapshotter#149]
https://github.com/moby/buildkit/pull/1666#discussion_r489907766

We could just use the containerd libs for registry stuff

**Comment by tonistiigi** [comment]
Another question would be how to get mirrors/tls configuration etc. I'm not sure how authentication works atm, possibly needs some updates as well.

**Comment by ktock** [comment]
Now snapshotter plugin has containerd's RegistryHost-based registry logic.
https://github.com/containerd/stargz-snapshotter/pull/153
