### ISSUE TITLE
Q: Compatible with Windows Containers?

### ISSUE THREAD

**Issue by ntrappe-msft** [containerd/stargz-snapshotter#1536]
Is the Stargz Snapshotter compatible with Windows Container images? Or is it primarily meant for Linux container images like Alpine?

**Comment by ktock** [comment]
Current implementation of stargz-snapshotter relies on FUSE so it can run only on Linux. But [eStargz image](https://github.com/containerd/stargz-snapshotter/blob/94b12086ace4119e86d2db0d6343d7c734b56671/docs/estargz.md) is platform agnostic.

**Comment by ntrappe-msft** [comment]
Thanks for the info!
