### ISSUE TITLE
Too many goroutines causing full CPU for large images

### ISSUE THREAD

**Issue by strigazi** [containerd/stargz-snapshotter#156]
Hello,

(So if you click by accident ENTER on the title you have an issue created.)

When doing ctr-remote i rpull for `docker.io/stargz/python:3.7-esgz` around 25K goroutines get created, then they go away (after ~30s).

For larger images like `docker.io/strigazi/ciadm:v0.3.9-esgz-bash-version` (OR `ghcr.io/strigazi/ciadm:v0.3.9-esgz-bash-version`) I get close to 1M goroutines that after 10mins they were still there. All 16 cores of my host get consumed from the snapshotter at 100%. I have an even larger image, I will try push it to docker.io, I have it locally for now.

I can pass you the profile from pprof if you need.

**Comment by strigazi** [comment]
cc @rochaporto @ktock

**Comment by strigazi** [comment]
From pprof I think that the routines get created  here [0] and they close only when all files are traversed.

[0] https://github.com/containerd/stargz-snapshotter/blob/8f2e7ec8468e67ed7251709af7841c6ca5ac64d6/stargz/reader/reader.go#L150

**Comment by ktock** [comment]
@strigazi Thanks for reporting this. Stargz snapshotter aggressively pulls and decompresses a layer in background aside from fetching contents on demand. These goroutines do this "background pull/decompression" per file. 
I wrote a patch to avoid too many goroutines there.

If you don't want snapshotter to pull/decompress layers in background, you can disable it by adding `no_background_fetch = true` to snapshotter's `config.toml`. File contents won't be fetched until access to that file occurs.

**Comment by strigazi** [comment]
> @strigazi Thanks for reporting this. Stargz snapshotter aggressively pulls and decompresses a layer in background aside from fetching contents on demand. These goroutines do this "background pull/decompression" per file.
> I wrote a patch #157 to avoid too many goroutines there.
> 
> If you don't want snapshotter to pull/decompress layers in background, you can disable it by adding `no_background_fetch = true` to snapshotter's `config.toml`. File contents won't be fetched until access to that file occurs.

I tried this config option, but I see the same behaviour (all cores consumed, too many goroutines)

**Comment by strigazi** [comment]
Fixed by #157
