### ISSUE TITLE
ino reuse in newInodeWithID

### ISSUE THREAD

**Issue by iain-macdonald** [containerd/stargz-snapshotter#1594]
At BuildBuddy, we run a modified version of the [soci-snapshotter](https://github.com/awslabs/soci-snapshotter) with the `store/` directory from stargz-snapshotter patched in to support podman as described [here](https://www.buildbuddy.io/blog/image-streaming). We recently encountered a bug caused by podman pulling two images in parallel in very quick succession (<1ms). I tracked it down to apparent ino reuse, hitting [this error](https://github.com/containerd/stargz-snapshotter/blob/6e5d5a0d2769b5fa7e72edfd5df403ad37ebb838/store/fs.go#L244) (note: the error message is incorrect, it should say `refnode` instead of `rootnode`, I can send a fix for this). Upon digging deeper, I discovered that the [logic in idMap](https://github.com/containerd/stargz-snapshotter/blob/6e5d5a0d2769b5fa7e72edfd5df403ad37ebb838/store/fs.go#L637-L647) which attempts to reuse inos sometimes offers recently claimed inos for reuse. This is because the check for whether an inode is active calls [`Inode.Forgotten()`](https://github.com/hanwen/go-fuse/blob/e9e7c22af17af4611b5783a16458647088cc8dec/fs/inode.go#L255) which returns `true` for newly created, unused, non-persistent inodes (because lookupcount is 0 and parents is empty).

Practically, this means that if an refnode Inode has been created but not yet returned to the caller, and a second refnode.Lookup call attempts to mint a new ino, then the code will return the same ino for both of those Inodes (because the first one is `releasable()`), causing the fuse operations for the first Inode to route incorrectly, causing errors in stargz-snapshotter. You can tickle this bug by adding a `time.Sleep()` in `newInodeWithID` between when the Inode is created and when it is returned, and then getting that code to run twice in parallel by e.g. pulling images externally.

I think a reasonable fix is to only attempt to reuse inos after `max` loops all the way around, which should create a pretty big buffer time between when inos are initially allocated and when the snapshotter attempts to reuse them. In most cases I suspect that would prevent ino reuse, but maybe there are some cases where we're loop through all 4B inos. I'm open to other suggestions as well. Let me know what you think.

**Comment by ktock** [comment]
Thanks for reporting this. I'm trying to fix this in #1599 .
