### ISSUE TITLE
Incorrect log message in store/fs.go

### ISSUE THREAD

**Issue by iain-macdonald** [containerd/stargz-snapshotter#1612]
I believe the log message on [line 244 of store/fs.go](https://github.com/containerd/stargz-snapshotter/blob/6e5d5a0d2769b5fa7e72edfd5df403ad37ebb838/store/fs.go#L244) is incorrect. Instead of saying "rootnode.Lookup: uknown node type detected" it should say "**refnode**.Lookup: uknown node type detected" as it's a method on refnode. I [opened a PR](https://github.com/containerd/stargz-snapshotter/pull/1595) to fix this, but I can't request a reviewer as I don't have write access to the containerd/stargz-snapshotter repository.

**Comment by ktock** [comment]
Fixed in https://github.com/containerd/stargz-snapshotter/pull/1595
