### ISSUE TITLE
Expose an estargz.Option for compression level

### ISSUE THREAD

**Issue by mattmoor** [containerd/stargz-snapshotter#200]
https://pkg.go.dev/github.com/containerd/stargz-snapshotter@v0.2.0/estargz#Option

I'm guessing that as a compatible gzip format, the notion of compression level should persist.  The standard library exposes this level, and the following enums: https://godoc.org/compress/gzip#pkg-constants

In GGCR we generally bias towards `gzip.BestSpeed`, but we expose an option for this in our own utilities around gzip.  It would be nice to preserve this optionality with estargz.

**Comment by ktock** [comment]
Though the [footer](https://github.com/containerd/stargz-snapshotter/blob/6ed3e72ebbc0d5f67f2b3eb16787f7e1a2890f05/docs/stargz-estargz.md#footer) must be gzip.NoCompression, we can expose compression level of other components (entries and toc).

**Comment by ktock** [comment]
I meant that I totally agree with the suggestion :smile:

**Comment by ktock** [comment]
Closing this as we support `WithCompression` option since  #201.
