### ISSUE TITLE
update Go to 1.15

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/stargz-snapshotter#202]
In #197 we tried to bump up Go from 1.13 to 1.15, but we failed because of the following FUSE error during `make benchmark`:

> writer: Write/Writev failed, err: 2=no such file or directory. opcode: INTERRUPT

Needs analysis and fix.

**Comment by AkihiroSuda** [comment]
@ktock Did you manage to analyze this? Go 1.16 will be also released soon.

**Comment by ktock** [comment]
Not yet.. I'll look into this deeper in this week.
