### ISSUE TITLE
Expose the Diff ID of the estargz bytes

### ISSUE THREAD

**Issue by mattmoor** [containerd/stargz-snapshotter#204]
Unfortunately, to assemble a container image, we need both the "Diff ID" (sha256 of uncompressed) and the digest (sha256 of compressed) to construct the config and manifest respectively.

Even though estargz is presented with the uncompressed tarball, we cannot use the sha256 of this as the "Diff ID" because estargz augments and reorders things.

This means that in order to get the "Diff ID" to assemble an image we must first compress the tarball with estargz and then decompress it with gunzip in order to compute the "Diff ID".

To optimize this path, in the original stargz implementation, @jonjohnsonjr had @bradfitz expose a DiffID method that could be accessed via type assertion and called to access the DiffID without the extra file scan: https://github.com/google/crfs/blob/12599487789fa1d5abead897932c40a1a17929dd/stargz/stargz.go#L798-L802

In a perfect world, the `io.ReadCloser` returned by `estargz.Build` would have a similar method on it that may be called once the stream has closed.

**Comment by ktock** [comment]
Closing this as this feature is added through #208.

**Comment by mattmoor** [comment]
Awesome, I'll take this for a spin after ☕ 

🤩
