### ISSUE TITLE
Consider dropping multierror

### ISSUE THREAD

**Issue by mattmoor** [containerd/stargz-snapshotter#205]
One thing that @jonjohnsonjr raised importing things downstream was the use of `github.com/hashicorp/go-multierror`, which also pulls in `github.com/hashicorp/errwrap`, but it seems like `estargz` could get away with something much simpler:

```go
// Errors provides an abstraction for accumulating multiple errors.
type Errors []error

// Append adds an error to the Errors
func (e *Errors) Append(err error) {
	*e = append(*e, err)
}

// Error implements error
func (e *Errors) Error() string {
	points := make([]string, len(*e)+1)
	points[0] = fmt.Sprintf("%d error(s) occurred:", len(*e))
	for i, err := range *e {
		points[i+1] = fmt.Sprintf("* %s", err)
	}
	return strings.Join(points, "\n\t")
}

var _ error = (*Errors)(nil)
```

I was experimenting with this here: https://play.golang.org/p/ALYdDsBRGjH

**Comment by AkihiroSuda** [comment]
SGTM, would you be interested in opening a PR?

**Comment by mattmoor** [comment]
I sent a PR that adds an adaptation of the above that makes "Append" support a nil receiver and return a new `*Errors`.
