### ISSUE TITLE
optimizer: imageio should use containerd native API

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/stargz-snapshotter#223]
https://github.com/containerd/stargz-snapshotter/blob/f045b42c062fac08ea440afc080de49765e2252d/converter/optimizer/imageio/imageio.go#L38-L44

@ktock 
For better integration with containerd, can we switch away from ggcr API into containerd content/image store API?
Especially, the converted image should be written to a containerd local image store without pushing.

**Comment by AkihiroSuda** [comment]
draft PR: https://github.com/containerd/stargz-snapshotter/pull/224

**Comment by AkihiroSuda** [comment]
Reopening. `ctr-remote images convert` is implemented, but `ctr-remote images optimize` still uses ggcr implementation.

**Comment by ktock** [comment]
After #238 is merged, I'll work on the refactoring of `ctr-remote image optimize` based on native converter + analyzer + containerd's registry lib. I'm thinking about how we can keep this working without running containerd daemon.

**Comment by AkihiroSuda** [comment]
>  I'm thinking about how we can keep this working without running containerd daemon.

Why not run the daemon?

Anyway, we could implement a static optimizer that parses ELF and shell scripts to estimate file dependencies without running any container at all, though its robustness would be limited.

**Comment by jonjohnsonjr** [comment]
> Anyway, we could implement a static optimizer that parses ELF and shell scripts to estimate file dependencies without running any container at all, though its robustness would be limited.

This sounds really interesting, especially if it's possible (and easy) for you to keep something like this decoupled from containerd.
