### ISSUE TITLE
Shapshotter Plugin: failed to cleanup when exit

### ISSUE THREAD

**Issue by mc256** [containerd/stargz-snapshotter#239]
## Motivation

If I did **not** run **any** `rpull` before exiting the GRPC plugin process. The log shows:
 
```
{"level":"info","msg":"Got SIGINT","time":"2021-01-09T22:29:53.085451014-05:00"}
{"level":"debug","msg":"Closing the snapshotter","time":"2021-01-09T22:29:53.085530254-05:00"}
{"error":"bucket does not exist: not found","level":"warning","msg":"failed to cleanup","time":"2021-01-09T22:29:53.085561794-05:00"}
{"level":"info","msg":"Exiting","time":"2021-01-09T22:29:53.085585104-05:00"}
```

It shows bucket does not exists. But I don't think it fails to cleanup. It is just because we have never created a bucket in `metadata.db`. If we `ctr-remote i rpull` an image and then `ctr-remote i rm` that image. It shows:

```
{"level":"info","msg":"Got SIGINT","time":"2021-01-09T22:37:18.002212584-05:00"}
{"level":"debug","msg":"Closing the snapshotter","time":"2021-01-09T22:37:18.002254534-05:00"}
{"level":"debug","msg":"cleanup: dirs=[]","time":"2021-01-09T22:37:18.002316464-05:00"}
{"level":"info","msg":"Exiting","time":"2021-01-09T22:37:18.002353864-05:00"}
```

## Suggestion

Should we create the bucket whenever we start the GRPC process? For example, I was thinking add initialization to function `snapshot/snapshot.go -> NewSnapshotter()`. Is that a good idea? Please let me know if this worth fixing. It exits with code 0 so it is not a problem. It comes up just because I may not use stargz and the warning message is a bit annoying.

**Comment by ktock** [comment]
> Should we create the bucket whenever we start the GRPC process? For example, I was thinking add initialization to function snapshot/snapshot.go -> NewSnapshotter(). Is that a good idea? Please let me know if this worth fixing. It exits with code 0 so it is not a problem. It comes up just because I may not use stargz and the warning message is a bit annoying.

If the purpose is just to avoid `error` message, I don't think we need to introduce initialization. Why not just ignore `bucket does not exist` (ideally this message should be printed as `Debug` log at least)?
