### ISSUE TITLE
Mind cutting another release?

### ISSUE THREAD

**Issue by jonjohnsonjr** [containerd/stargz-snapshotter#244]
[Our dependency](https://github.com/google/go-containerregistry/blob/213dd48b6cf3d6139a9787781e0e24ff2c4a0f56/go.mod#L10) on github.com/containerd/stargz-snapshotter/estargz isn't included in any release yet.

If it's not too much trouble, it would help me with updating some other dependencies if you could cut another release at some point.

Thanks!

**Comment by ktock** [comment]
Current on-going patches are #243 and #240 but I think we don't need to include them to the immediate next release. So we can release v0.3.0 soon.

@AkihiroSuda WDYT?

**Comment by AkihiroSuda** [comment]
LGTM

**Comment by ktock** [comment]
v0.3.0 is out :tada:

**Comment by ktock** [comment]
https://github.com/containerd/stargz-snapshotter/releases/tag/v0.3.0

**Comment by jonjohnsonjr** [comment]
Thank you :)
