### ISSUE TITLE
Issues with containerd 1.4.3

### ISSUE THREAD

**Issue by siscia** [containerd/stargz-snapshotter#251]
Hi guys,

while our snapshotter keep working with 1.4.0 it seems to have troubles with 1.4.3

The main issues seems to be the lack of labels, the snapshotter does not receives the labels and it doesn't know what to mount.

Are you guys seeing a similar behavior?

**Comment by ktock** [comment]
Hi, 
Did you add `disable_snapshot_annotations = false` option to config.toml?
This option is needed since v1.4.2.

e.g.

```tool
version = 2

# Plug stargz snapshotter into containerd
# Containerd recognizes stargz snapshotter through specified socket address.
# The specified address below is the default which stargz snapshotter listen to.
[proxy_plugins]
  [proxy_plugins.stargz]
    type = "snapshot"
    address = "/run/containerd-stargz-grpc/containerd-stargz-grpc.sock"

# Use stargz snapshotter through CRI
[plugins."io.containerd.grpc.v1.cri".containerd]
  snapshotter = "stargz"
  disable_snapshot_annotations = false
```
https://github.com/containerd/stargz-snapshotter#quick-start-with-kubernetes

**Comment by siscia** [comment]
Got it!

I was just looking into it!

Thanks!
https://github.com/containerd/containerd/pull/4665

A related question, do you think our snapshotter should work also with `nerdctl` ?

**Comment by ktock** [comment]
Thanks for looking at nerdctl.
If your snapshotter works with our `ctr-remote image rpull` command, it should work without patches.
But you need to register your snapshotter to containerd with the name containing the string `stargz`.
If your snapshotter uses labels other than ones used by Stargz Snapshotter, the patch will be needed for nerdctl.

ref: https://github.com/AkihiroSuda/nerdctl/blob/v0.5.0/pkg/imgutil/imgutil.go

cc: @AkihiroSuda
