### ISSUE TITLE
CI: remove dependency on Docker CLI

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/stargz-snapshotter#272]
The current CI uses both `nerdctl` and `docker` CLI.

The new release of `nerdctl` supports `nerdctl login` (thanks to @fahedouch), so dependency on Docker CLI should be now removable: https://github.com/AkihiroSuda/nerdctl/releases/tag/v0.6.0

**Comment by ktock** [comment]
Thanks, I'll work on this.
