### ISSUE TITLE
README.md should have a link to pre-converted-images.md

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/stargz-snapshotter#279]
https://github.com/containerd/stargz-snapshotter/blob/v0.4.1/docs/pre-converted-images.md is hard to find , should be linked from the top README.md

**Comment by MadhavJivrajani** [comment]
Hey, if I understand correctly, that particular section of docs is linked in [this](https://github.com/containerd/stargz-snapshotter/tree/v0.4.1#creating-estargz-images-with-optimization) section of the main README.md. Or would you want it linked in the beginning of the main README?

**Comment by AkihiroSuda** [comment]
Didn't notice that it is already linked in README. Currently too hard to find.
