### ISSUE TITLE
The plugin should fail early when prerequisites are not satisfied

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/stargz-snapshotter#280]
For ease of debugging the broken installation, the plugin should fail early when critical prerequisites are not satisfied, e.g., 

- `fusermount` is not present in the $PATH
- `/var/lib/containerd-stargz-grpc` is mounted with an incompatible FS (such as `overlayfs`)

**Comment by ktock** [comment]
We should add the logic here:

https://github.com/containerd/stargz-snapshotter/blob/6122c3ed78d7a361e05b56a062fc4622d2c69ac5/service/service.go#L127-L137

And we should call this function at main package of `containerd-stargz-grpc`.
