### ISSUE TITLE
standardize lazy pulling enabled image format in oci spec

### ISSUE THREAD

**Issue by liubogithub** [containerd/stargz-snapshotter#284]
Hi,

The project that I'm working on is called [Nydus](https://github.com/dragonflyoss/image-service).  (also mentioned in #182)

On the "Container Plumbing Conference", @bergwolf did a brief introduction about Nydus and @ktock did one about estargz/zstd:chunked.  I think both estargz and nydus are solving the exactly same problems and share similar design ideas underneath as well.

We believe that lazy pulling enabled image format can make a big difference for the container practice (we've also proven that internally), so I'm looking forward to making oci image spec support such kind of format officially.

Here I'd like to open an issue to discuss how we can starting work together.  Any comments/thoughts are welcome.

**Comment by AkihiroSuda** [comment]
Yes, this is discussed in https://github.com/opencontainers/image-spec/issues/815

**Comment by liubogithub** [comment]
Thanks for the link, somehow I missed that, will take a look.
Let's move discussion there as well.
