### ISSUE TITLE
How to manager cache in disk?

### ISSUE THREAD

**Issue by luodw** [containerd/stargz-snapshotter#308]
Hello, I see stargz-snapshotter cache blob file in disk，but in snapshotter remove and cleanup method, it do not remove the blob cache file, so how to do when cache blob file grow and hit the disk size? 

And if remove blob cache file in snapshotter,  it will not be suitable with kubelet.  As kubelet will check the disk presure, if disk usage is hit the threshold, kubelet will evict container and image via cri。However with stargz-snapshotter, containerd only remove snapshot dir, not remove blob cache file. Maybe containerd should expose remote content store as remote snapshotter?

**Comment by ktock** [comment]
I agree with that we need GC of cache contents for unused snapshots. This is currently WIP on https://github.com/containerd/stargz-snapshotter/pull/276.

**Comment by luodw** [comment]
@ktock  maybe layer and blob reference relation should persist to disk?  how to do when stargz-snapshotter restart?

**Comment by ktock** [comment]
> maybe layer and blob reference relation should persist to disk?

@luodw Yes, we need to work on this.

Currently we are working on enabling cleanup in #309 but it doesn't include support for restart.
