### ISSUE TITLE
[Discussion] Disk writes while fetching data from remote registry

### ISSUE THREAD

**Issue by sumeetb25** [containerd/stargz-snapshotter#328]
Hello Container community,

I am pretty new to the container ecosystem and in the early stages of exploring stargz snapshotter. Based on my understanding of the Mount path of stargz snapshotter following things happen:

1. For each layer snapshotter downloads compressed tarball as chunks (size is configurable, defaults to 50KiB) and writes compressed data to /var/lib/containerd-stargz-grpc/stargz/httpcache/...
2. After the download and writes complete it loops through the TOC entries, reads compressed data for each regular file, decompresses that data and stores it to /var/lib/containerd-stargz-grpc/stargz/fscache/...

If my understanding is accurate, this workflow implies the snapshotter will write compressed data to disk in step 1, then read that data from disk in step 2, decompress that data and finally write it again at a different path to disk. This incurs three disk operations.

I would like to get the communities thoughts on optimizing this workflow as follows - Instead of writing compressed data to disk we decompress it right away and only write the decompressed data to disk. This would reduce 2 disk operations. 

I haven’t done any benchmarks with this approach yet. Wanted to reach out to see if there are any obvious gotchas that I should be aware of.

**Comment by ktock** [comment]
> Instead of writing compressed data to disk we decompress it right away and only write the decompressed data to disk.

Yes, I agree with this.

We should also care about reducing the number of requests to the registry. Currently, when a small file A is requested from a container, the neighbouring files are (pre)fetched as well in one (50KB) request and cached to ` /var/lib/containerd-stargz-grpc/stargz/httpcache/`. This behaviour should be preserved even after we refactor the cache structure.

**Comment by sumeetb25** [comment]
> > Instead of writing compressed data to disk we decompress it right away and only write the decompressed data to disk.
> 
> Yes, I agree with this.
> 
> We should also care about reducing the number of requests to the registry. Currently, when a small file A is requested from a container, the neighbouring files are (pre)fetched as well in one (50KB) request and cached to ` /var/lib/containerd-stargz-grpc/stargz/httpcache/`. This behaviour should be preserved even after we refactor the cache structure.

Ack.
