### ISSUE TITLE
Allow fusermount3

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/stargz-snapshotter#340]
https://github.com/containerd/stargz-snapshotter/blob/e9306b199a1b48a44ac68f7af1d844386e4ca304/store/fs.go#L53

On Fedora 34, the binary name is `fusermount3`, not `fusermount`

**Comment by ktock** [comment]
@AkihiroSuda go-fuse doesn't support `fusermount3` as of now https://github.com/hanwen/go-fuse/pull/356.
When `fusermount` is not found on the system, snapshotter will fallback to `DirectMount` mode that doesn't use `fusermount`.
Doesn't it work on Fedora 34?

**Comment by ktock** [comment]
It seems that go-fuse added support of `fusermount3` (https://github.com/hanwen/go-fuse/commit/934a183ed91446d218b5471c4df9f93db039f6e1) so now we can fix our implementation to use `fusermount3`.
