### ISSUE TITLE
Allow users to manually enabled single range mode for fetcher using config

### ISSUE THREAD

**Issue by rdpsin** [containerd/stargz-snapshotter#348]
Stargz-snapshotter has a mechanism to support registries that do not allow multiple ranges in a single GET request. For the fallback mechanism to kick in, the snapshotter expects the registry to return an error.

Some registries like AWS ECR neither support retrieving multiple ranges of data per GET request nor return an error. Instead they send back the entire requested object.

I propose changes that allow users to manually set the fetcher to single range mode using a field in the config.

Changes:

1) fs/config/config.go: Add a field 'ForceSingleRangeMode' in BlobConfig, corresponding to 'force_single_range_mode' in config.toml
2) fs/remote/resolver.go: Check whether blobConfig.ForceSingleRangeMode is true; if it is, the fetcher is set to single range mode using fetcher.singleRangeMode()

You can see the commit here: https://github.com/rdpsin/stargz-snapshotter/commit/92123b53c0ff37c07bc2a80084c19b347c99716c

**Comment by ktock** [comment]
Thank you for the suggestion.  Could you open up the PR?

**Comment by ktock** [comment]
Solved in https://github.com/containerd/stargz-snapshotter/pull/350
