### ISSUE TITLE
Enable GPU support and net-host inside container when optimizing

### ISSUE THREAD

**Issue by rdpsin** [containerd/stargz-snapshotter#381]
Currently, networking inside a container when optimizing through the ctr-remote tool is only
available through CNI-based networking plugins, not through `net-host`, which is often quite simpler. Furthermore, there is no option to enable GPUs inside the container when optimizing GPU-based images.

I propose changes to adds flags to the optimize command to enable both features.

The changes can be seen in: https://github.com/rdpsin/stargz-snapshotter/commit/54b9be6efbf45fd7c59f7976d854c72e421785ba

**Comment by ktock** [comment]
SGTM

**Comment by ktock** [comment]
Added in https://github.com/containerd/stargz-snapshotter/pull/382
