### ISSUE TITLE
How to inspect state directory to monitor on-demand filesystem errors

### ISSUE THREAD

**Issue by iamsumee** [containerd/stargz-snapshotter#405]
Hi All,

The documentation [here](https://github.com/containerd/stargz-snapshotter/blob/main/docs/overview.md#state-directory) mentions the presence of hidden `state` directory at the root of the filesystem. Unfortunately I do not see any such directory at the root file system path.

```
[iamsumee@ip-10-0-56-202 stargz-snapshotter]$ ls /.stargz-snapshotter/*
ls: cannot access /.stargz-snapshotter/*: No such file or directory
```

Can someone please help me with the steps to locate the `state` directory. It will be super useful to monitor any on-demand filesystem errors by inspecting state directory contents.

**Comment by ktock** [comment]
@iamsumee You can inspect `state` directory inside the lazily-pulled container:

```console
# nerdctl --snapshotter=stargz run --rm -it ghcr.io/stargz-containers/python:3.9-esgz /bin/bash -c 'ls /.stargz-snapshotter/*'
/.stargz-snapshotter/sha256:175e214189fae42010e89f1bf46c52360b90e3f1456541adac4f8003d833d7fa.json  /.stargz-snapshotter/sha256:3a05ce7e878ca563bbe59c9b0a3af4b2b5f89c01db1efffbefe29d45570c8abb.json  /.stargz-snapshotter/sha256:9a9685d7064c1b7c155b932352d01655b78baf933e67fca2005b9d3eb33dac1d.json
/.stargz-snapshotter/sha256:2d9b2276a5565f17aa5e87a15e32afa03db427fbf2c25509f8f297c52158f21f.json  /.stargz-snapshotter/sha256:6dd3cdbca7c4d039837d885172606dab65d3b03f721b99656247b10291285411.json  /.stargz-snapshotter/sha256:b41f5d611b99625bb6957c45498870ed4eb67361a35db209d83647c24f29e0b0.json
/.stargz-snapshotter/sha256:34a0e91c90c6d3dc238807fac8d4640ee55c7abe1137b48cef2d3810bb9744f2.json  /.stargz-snapshotter/sha256:847c5e6091f0cabbb55097c68df60c86c3619e9eaabe7b64b1471bb62d88779f.json  /.stargz-snapshotter/sha256:e822847ac5922e5be7c0aedd8226e9826ba6ddaf897d7fc303d6f0d937df6a99.json
```

Or you can inspect state files of each snapshot under the snapshotter root dir (tipically /var/lib/containerd-stargz-grpc) on the host:

```console
# ls /var/lib/containerd-stargz-grpc/snapshotter/snapshots/1/fs/.stargz-snapshotter/*
/var/lib/containerd-stargz-grpc/snapshotter/snapshots/1/fs/.stargz-snapshotter/sha256:6dd3cdbca7c4d039837d885172606dab65d3b03f721b99656247b10291285411.json
```

**Comment by iamsumee** [comment]
Unfortunately I do not see the state directory at either the host or within the container.

```
[iamsumee@ip-10-0-56-202 ~]$ sudo ./stargz-snapshotter/out/ctr-remote run --snapshotter=stargz --net-host $IMAGE container-id11 ls /.stargz-snapshotter/*
.......
<A bunch of startup log lines>
....
Started new task pid=31384 duration=15741431
Waiting for status result pid=31384
ls: cannot access '/.stargz-snapshotter/*': No such file or directory
```

At the host:
```
[iamsumee@ip-10-0-56-202 stargz-snapshotter]$ sudo ls -la /var/lib/containerd-stargz-grpc/snapshotter/snapshots/1/fs/.stargz-snapshotter/*
ls: cannot access /var/lib/containerd-stargz-grpc/snapshotter/snapshots/1/fs/.stargz-snapshotter/*: No such file or directory
```

If it helps following is the content of my `config.toml`

```
max_concurrency = 10
```

**Comment by ktock** [comment]
@iamsumee 

> ls: cannot access '/.stargz-snapshotter/*': No such file or directory

`*` seems escaped incorrectly?

Could you try `/bin/bash -c 'ls /.stargz-snapshotter/*'`?

```
ctr-remote run --snapshotter=stargz --net-host $IMAGE container-id11 /bin/bash -c 'ls /.stargz-snapshotter/*'
```

**Comment by vkuzniet** [comment]
@ktock, thank you for your help!
I was able to access it:
`
[ec2-user@ip-172-31-79-103 ~]$ sudo ./stargz-snapshotter/out/ctr-remote run --snapshotter=stargz --net-host $IMAGE container-id14 /bin/sh -c 'ls /.stargz-snapshotter/*'
/.stargz-snapshotter/sha256:b351995b18968208fc25eebd647205694d04876db60d4d79a67d1cc8ff50f4ff.json
/.stargz-snapshotter/sha256:c95ee4aba5b02db7bbf46410c26754b42ea8ce1cfbbdc40764f96fc6f044c30b.json
`

`
[ec2-user@ip-172-31-79-103 ~]$ sudo ./stargz-snapshotter/out/ctr-remote run --snapshotter=stargz --net-host $IMAGE container-id15 /bin/sh -c 'cat /.stargz-snapshotter/*'
{"digest":"sha256:b351995b18968208fc25eebd647205694d04876db60d4d79a67d1cc8ff50f4ff","size":775792,"fetchedSize":775792,"fetchedPercent":100}
{"digest":"sha256:c95ee4aba5b02db7bbf46410c26754b42ea8ce1cfbbdc40764f96fc6f044c30b","size":680,"fetchedSize":680,"fetchedPercent":100}
`

**Comment by vkuzniet** [comment]
One more question though. Having the state directories within the container file system is good, but doesn't help when troubleshooting production issues, since there's a high likelihood that you may not have access there.
So the question is, does snapshotter persist the same data on the host where it's installed? That would be really helpful.
Note: I tried looking the files within `/var/lib/containerd-stargz-grpc/*` with no luck.

**Comment by ktock** [comment]
> does snapshotter persist the same data on the host where it's installed?

No it doesn't so far. Maybe we can print the contents of the state directory as a log when an error occur in the filesystem.

**Comment by vkuzniet** [comment]
That works. Thank you!

**Comment by ktock** [comment]
This seems resolved. Closing.
