### ISSUE TITLE
Could stargz format be compatible to Docker Image Manifest V2?

### ISSUE THREAD

**Issue by RobberPhex** [containerd/stargz-snapshotter#473]
There is some legacy Kubernetes cluster is using Docker <v19.03.0, which is not support OCI image.

So, Could stargz format image be stored in [Docker Image Manifest V2](https://docs.docker.com/registry/spec/manifest-v2-2/) image?

**Comment by ktock** [comment]
Yes eStargz is compatible to Docker images as well.
If the source image is Docker image, `ctr-remote` preserves the image format unless you specifiy `--oci` option.
