### ISSUE TITLE
Use of `--reuse` option during `ctr-remote i optimize`

### ISSUE THREAD

**Issue by rdpsin** [containerd/stargz-snapshotter#490]
Hello,

I'm bit confused about the `reuse` flag available when optimizing images. It allows the tool to skip over already existing eStargz layers in the image. I'm curious what the use case is? Authoring new images using an eStargz image as base image (`docker` and `podman` strip away annotations when pulling eStargz images, so eStargz images are still converted)? 

Thanks.

**Comment by ktock** [comment]
> new images using an eStargz image as base image

Yes, they are the major use-cases of that flag.

> docker and podman strip away annotations when pulling eStargz images, so eStargz images are still converted

We should fix the `ctr-remote` implementation to avoid recreation of such layers and generate only necessary annotations.

**Comment by ktock** [comment]
> Aren't the layer annotations necessary to determine if a layer is eStargz or not? 

Yes, they are.

> The current implementation needs at least containerd.io/snapshot/stargz/toc.digest to get the digest and verify eStargz layers.

`io.containers.estargz.uncompressed-size` is also added so that podman can perform lazy pulling.

https://github.com/containerd/stargz-snapshotter/blob/4fe81f7a9e4d90054c867475148bf2b0abfa8448/nativeconverter/estargz/estargz.go#L150-L151

**Comment by ktock** [comment]
@rdpsin Have you tried the recent BuildKit (or Docker Buildx) ?
It now supports estargz.

https://github.com/moby/buildkit/blob/8778943ac3da296d144319618f86a6c46fcc5eba/docs/stargz-estargz.md#creating-stargzestargz-images

NOTE: master version of BuildKit supports estargz but it's not released yet.

```
$ docker buildx create --use --name latest \
         --driver docker-container \
         --driver-opt image=moby/buildkit:master
$ docker buildx inspect --bootstrap latest
$ docker buildx build \
       -o type=registry,name=ghcr.io/ktock/ubuntu:20.04-hello-esgz,oci-mediatypes=true,compression=estargz \
       /tmp/context/
$ crane manifest ghcr.io/ktock/ubuntu:20.04-hello-esgz  | jq
{
  "mediaType": "application/vnd.oci.image.manifest.v1+json",
  "schemaVersion": 2,
  "config": {
    "mediaType": "application/vnd.oci.image.config.v1+json",
    "digest": "sha256:d89c28c9e6579837b45760e0a2fae54e3f4ed34b71a175b39b1c4e673ac26dd8",
    "size": 2919
  },
  "layers": [
    {
      "mediaType": "application/vnd.oci.image.layer.v1.tar+gzip",
      "digest": "sha256:93ef9da9c5f3db2ac7fd52cab0e63c7e6fc9a722aec43d1b936a130e979ab8e8",
      "size": 30387427,
      "annotations": {
        "containerd.io/snapshot/stargz/toc.digest": "sha256:3e48bc557bbef7bb5d05086f8555201e30644ce82ca78d5973fb897b5577c52e",
        "io.containers.estargz.uncompressed-size": "76116480"
      }
    },
    {
      "mediaType": "application/vnd.oci.image.layer.v1.tar+gzip",
      "digest": "sha256:ea8aeca69d07706fb87e659f5303278f0a416188e69e14eaecc08e41f4cb6ca0",
      "size": 3062,
      "annotations": {
        "containerd.io/snapshot/stargz/toc.digest": "sha256:dfa0236c7930ed7d5c3071a2d2cbda1e0b0c28408397ba91576e190488774f95",
        "io.containers.estargz.uncompressed-size": "22016"
      }
    },
    {
      "mediaType": "application/vnd.oci.image.layer.v1.tar+gzip",
      "digest": "sha256:61a9dd44cb77a78807152f401650d8a5233cf1cbc67c736e2c6d495704462076",
      "size": 805,
      "annotations": {
        "containerd.io/snapshot/stargz/toc.digest": "sha256:74576d7732f0b33710a4b60a68fa830e815b6b4de394f62d1297372666d53652",
        "io.containers.estargz.uncompressed-size": "6656"
      }
    },
    {
      "mediaType": "application/vnd.oci.image.layer.v1.tar+gzip",
      "digest": "sha256:69e02c02f098aeb6202dd7b90b5fd388772955a42732ea6ccc2ec711559b8368",
      "size": 489,
      "annotations": {
        "containerd.io/snapshot/stargz/toc.digest": "sha256:4373296357b1fd1227650ac8b0fcf41b3a7ff861e719f57c2a78c9639a4d9125",
        "io.containers.estargz.uncompressed-size": "4096"
      }
    }
  ]
}
```
