### ISSUE TITLE
Location of v0.10.0 estargz node kind image?

### ISSUE THREAD

**Issue by csantanapr** [containerd/stargz-snapshotter#518]
I was wondering if the new version `v0.10.0` image was going to be posted? `ghcr.io/stargz-containers/estargz-kind-node:0.10.0`

I checked and is not available
```
❯ crane ls ghcr.io/stargz-containers/estargz-kind-node
0.7.0
0.8.0
0.9.0
```

**Comment by ktock** [comment]
Thank you for reporting this. Published `0.10.0`. https://github.com/orgs/stargz-containers/packages/container/estargz-kind-node/10002580?tag=0.10.0

You can also build any versions of images by running `docker build` using our Dockerfile https://github.com/containerd/stargz-snapshotter/blob/main/Dockerfile.

**Comment by csantanapr** [comment]
Thank so much @ktock 

I didn't see the Dockerfile thanks for letting me know.

**Comment by ktock** [comment]
Thank you for your reporting. Closing this.
