### ISSUE TITLE
Unexpected error since nerdctl v0.14.0

### ISSUE THREAD

**Issue by aledbf** [containerd/stargz-snapshotter#537]
I see this error since nerdctl v0.14.0
```
Nov 24 16:56:19 workspace-pool-fx6p containerd-stargz-grpc[884]: Failed to obtain reader, failed to marshal fields to JSON, json: unsupported type: func() (io.ReadCloser, error)
```

I am using a similar approach to https://github.com/kubernetes-sigs/kind/pull/2076 to configure starts
maybe I am doing something wrong?

**Comment by ktock** [comment]
#539 might be related to this.

Could you elaborate on the issue?

- What command did you run and what result did you get when the error is logged?
- Could you provide lines of logs around `Failed to obtain reader`?

**Comment by aledbf** [comment]
Closing. I cannot reproduce with latest version
