### ISSUE TITLE
Image request: nixos/nix

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/stargz-snapshotter#546]
https://hub.docker.com/r/nixos/nix/

:pray:

**Comment by ktock** [comment]
:+1:
 `ghcr.io/stargz-containers/nixos/nix:2.3.12-org`

https://github.com/orgs/stargz-containers/packages/container/nixos%2Fnix/11118837?tag=2.3.12-org

**Comment by AkihiroSuda** [comment]
Thx, could you update to v2.5.0
(Btw maybe it's good time to update other images too)

**Comment by ktock** [comment]
> v2.5.0

https://github.com/orgs/stargz-containers/packages/container/nixos%2Fnix/11938468?tag=2.5.0-org

>  (Btw maybe it's good time to update other images too)

I'll work on it.
