### ISSUE TITLE
service name confusion 

### ISSUE THREAD

**Issue by jonyhy96** [containerd/stargz-snapshotter#560]
stargz-snapshotter show logs like:
```bash
Dec 13 10:01:55 stargz-demo-control-plane containerd-stargz-grpc[192]
```
but u should use `journalctl -u stargz-snapshotter`  to see only snapshotter's log. it may confused if it is not `journalctl -u containerd-stargz-grpc`

maybe the names on both sides should be consistent.

**Comment by ktock** [comment]
You can change the service name by your own

```
sudo mv /etc/systemd/system/stargz-snapshotter.service /etc/systemd/system/containerd-stargz-grpc.service
```
