### ISSUE TITLE
no state directory

### ISSUE THREAD

**Issue by fannaihao** [containerd/stargz-snapshotter#595]
I  am concerned about how much data has been pull to local.
According to  https://github.com/containerd/stargz-snapshotter/blob/main/docs/overview.md , it should have a state directory under container's root path.
But I can't find any:
    command: 
    `ctr-remote images rpull --snapshotter=stargz iregistry.harbo.com/research/wordpress-estargz:latest`
    `ctr-remote run --rm -t --snapshotter=stargz iregistry.harbo.com/research/wordpress-estargz:latest  test /bin/bash`
    ` cat /.stargz-snapshotter/*`
    output: 
    `cat: '/.stargz-snapshotter/*': No such file or directory`
    
My environment has install containerd & stargz-snappshotter & fuse successfully, and lazy pull has been observed, the only problem is that there is no state directory.

Any help will be appreciated !

**Comment by ktock** [comment]
@fannaihao Does it work with other images like `ghcr.io/stargz-containers/ubuntu:20.04-esgz` ?

```
# ctr-remote images rpull --snapshotter=stargz ghcr.io/stargz-containers/ubuntu:20.04-esgz
# ctr-remote run --rm -t --snapshotter=stargz ghcr.io/stargz-containers/ubuntu:20.04-esgz test /bin/bash
(in container)# cat /.stargz-snapshotter/*
```

Could you provide the log of `containerd-stargz-grpc` ?

**Comment by fannaihao** [comment]
> @fannaihao Does it work with other images like `ghcr.io/stargz-containers/ubuntu:20.04-esgz` ?
> 
> ```
> # ctr-remote images rpull --snapshotter=stargz ghcr.io/stargz-containers/ubuntu:20.04-esgz
> # ctr-remote run --rm -t --snapshotter=stargz ghcr.io/stargz-containers/ubuntu:20.04-esgz test /bin/bash
> (in container)# cat /.stargz-snapshotter/*
> ```
> 
> Could you provide the log of `containerd-stargz-grpc` ?

when I start the container, log prints:
`{"key":"default/296/test2","level":"debug","mount-point":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/26/fs","msg":"layer is normal snapshot(overlayfs)","time":"2022-01-20T14:19:27.154726108+08:00"}
{"key":"default/296/test2","level":"debug","mount-point":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/25/fs","msg":"layer is normal snapshot(overlayfs)","time":"2022-01-20T14:19:27.154767382+08:00"}`
why the layer(I have converted it) is recognized as an normal snapshot?

when I rpull an already converted image, from https://github.com/containerd/stargz-snapshotter/blob/main/docs/pre-converted-images.md , ghcr.io/stargz-containers/jruby:9.2.8.0-org, all things are pull,  log prints: 
`{"error":"failed to resolve layer \"sha256:4202cad047beb123fcec38e5826fcb4068d18d055f4cf7e03609632631cd7371\" from \"iregistry.harbor.com/research/jruby-stargz:latest\": failed to resolve the blob: failed to resolve the source: cannot resolve layer: failed to get size (host \"iregistry.harbor.com\", ref:\"iregistry.harbor.com/research/jruby-stargz:latest\", digest:\"sha256:4202cad047beb123fcec38e5826fcb4068d18d055f4cf7e03609632631cd7371\"): failed to fetch oauth token: authorization server did not include a token in the response: failed to resolve: failed to resolve target","key":"default/299/extract-17719527-jlYy sha256:4b50e1265409dbc28c8f71359c4cd42f55ec4c592027ce728bd10316669adf9d","level":"debug","mountpoint":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/109/fs","msg":"failed to resolve layer","parent":"","time":"2022-01-20T15:04:24.304407059+08:00"}`
looks like an authorization problem..

**Comment by ktock** [comment]
@fannaihao 

> why the layer(I have converted it) is recognized as an normal snapshot?

Lazy-pulling seems to fail on your node. How did you converted it? Cloud you provides the command lines you used for conversion?

> when I rpull an already converted image, from https://github.com/containerd/stargz-snapshotter/blob/main/docs/pre-converted-images.md , ghcr.io/stargz-containers/jruby:9.2.8.0-org,

Please use images that have `-esgz` suffix. i.e. Use `ghcr.io/stargz-containers/jruby:9.2.8.0-esgz` instead of `ghcr.io/stargz-containers/jruby:9.2.8.0-org`.

Does lazy pulling succeed using `ghcr.io` instead of `iregistry.harbor.com`?

**Comment by ktock** [comment]
@fannaihao How is this issue going?

**Comment by fannaihao** [comment]
Eventually, I find it's an auth problem that lead to stargz-snapshotter get image information from private http registry failed.
Solved following this: https://github.com/containerd/stargz-snapshotter/blob/main/docs/overview.md#registry-mirrors-and-insecure-connection

**Comment by fannaihao** [comment]
> How is this issue going?

Err message is:
`failed to fetch oauth token: authorization server did not include a token in the response`
I'm not sure if there is a problem with my registry?

**Comment by ktock** [comment]
Could you check you authorization server configuration?

https://github.com/containerd/containerd/blob/f033f6ff85ce397202ee69de22b4e3a4bf4093f5/remotes/docker/auth/fetch.go#L35-L37

```go
	// ErrNoToken is returned if a request is successful but the body does not
	// contain an authorization token.
```

**Comment by fannaihao** [comment]
> There is a doc about registry client configuration

I have put the registry auth token in `~/.docker/config.json`, It seems not work... There is still ErrNoToken error.

**Comment by ktock** [comment]
Please ensure `$DOCKER_CONFIG` for containerd-stargz-grpc set propery and reboot containerd-stargz-grpc daemon.

**Comment by ktock** [comment]
Closing as it's solved.
