### ISSUE TITLE
Combine with desync to support finer dedup.

### ISSUE THREAD

**Issue by sequix** [containerd/stargz-snapshotter#64]
desync supports mounting out a single file with a much smaller index (just like casync).
And I think that the single file can be a .stargz file, then we can mount it again, to have a proper directory tree. 
In this way, we can have lazy-pulling and dedup with minimal effort.
I know that this is not totally true. gz compression will mess up the chunking, but since .stargz is gzipped per file, this should not be a big concern.
What do you guys think?

**Comment by ktock** [comment]
@sequix Thanks for the proposal. I agree with that we can hopefully achieve finer deduplication using casync/desync-based storage(My initial attempt was based on this standpoint: https://github.com/ktock/container-bootfs). 
But unfortunately, supporting docker-incompatible backends/APIs is out-of-scope for this repo (please also see the discussion in the project proposal: https://github.com/containerd/project/issues/41 and https://github.com/containerd/project/issues/43). However, you can make another snapshotter using some components in this repo (e.g. [ remote snapshotter template](https://github.com/containerd/stargz-snapshotter/blob/master/snapshot/snapshot.go)).

**Comment by ktock** [comment]
Closing it because of the above reason. Very welcome for the further proposal.
