### ISSUE TITLE
Any stargz-snapshotter production environment use case

### ISSUE THREAD

**Issue by fannaihao** [containerd/stargz-snapshotter#702]
Do we have any production environment use case information about stargz-snapshotter?
I think it is an important means to advertise stargz-snapshotter and convince people : )

**Comment by ktock** [comment]
- Using stargz-snapshotter with variety of tools (e.g. Kubernetes, k3s, nerdctl(containerd), Podman/CRI-O, Kaniko, etc):  https://medium.com/nttlabs/lazy-pulling-estargz-ef35812d73de and #258
- Lazy pulling of base images (`FROM` instruction of Dockerfiles) on BuildKit: https://github.com/moby/buildkit/blob/master/docs/stargz-estargz.md
- Speeding up analysis pipelies which use gigabytes container images: https://kccncna20.sched.com/event/ekDj
- Lazy pulling of runner images on Argo Workflow https://github.com/containerd/stargz-snapshotter/tree/main/script/k3s-argo-workflow
