### ISSUE TITLE
[Discussion] Lazy pulling additonal flags

### ISSUE THREAD

**Issue by catric96** [containerd/stargz-snapshotter#716]
Hi, 

I was wondering if stargz-snapshotter can be configured to pull the entire image after what was required for the container to start is pulled. Let's say I'm trying to start a container with a estargz image, start it, but then would like to eventually have the whole image present after the container has already started with the minimal chunks of the image present. This way I would be safe in the event that the registry goes down and some other part of the container image would attempt to be pulled and fail. 

Would this be an option I can enable? Or does this happen by default? I was trying to dig through documentation and didn't find an answer that gave me 100% certainty. 

Thanks!

**Comment by ktock** [comment]
> pull the entire image after what was required for the container to start is pulled.

Yes, this is the default behaviour.
You can monitor the status of pulling at `/.stargz-snapshotter` in the container: https://github.com/containerd/stargz-snapshotter/blob/v0.11.3/docs/overview.md#state-directory

**Comment by ktock** [comment]
Closing this because this is answered by https://github.com/containerd/stargz-snapshotter/issues/716#issuecomment-1081264417
