### ISSUE TITLE
3 error(s) occurred  gzip: invalid header* legacy: failed to get footer gzip reader: gzip invalid header

### ISSUE THREAD

**Issue by yueyuep** [containerd/stargz-snapshotter#742]
when use  stargz snapshotter to pull private images on Kubernetes , it don't work, and just pull all layers.
i use kubectl create secret `regcred,`  then use  CRI-based authentication according to https://github.com/containerd/stargz-snapshotter/blob/main/docs/overview.md
`test_pol.yaml:`
the `registry.baidubce.com/stargz-work/wordpress-stargz-opt:latest` is stagz image
![image](https://user-images.githubusercontent.com/38725707/163943936-b00cd6c7-7ff7-4f68-812b-00876050cca2.png)

`/etc/containerd/conf.toml`
![image](https://user-images.githubusercontent.com/38725707/163945471-b4dd0344-ddce-4a08-a8d7-c8386cad6282.png)

`/etc/containerd-starhz-grpc/config.toml`
![image](https://user-images.githubusercontent.com/38725707/163945773-61dd65f7-bac0-4987-bf4c-aad47b1e0c06.png)

`systemctl status stargz-snapshotter.service ` 

![image](https://user-images.githubusercontent.com/38725707/163943446-76f5af73-badf-46d2-86ad-b8dd6fa8da19.png)

**Comment by yueyuep** [comment]
systemctl status stargz-snapshotter.service

![image](https://user-images.githubusercontent.com/38725707/163947129-d40c22e3-a860-4af1-a8af-04b017551fde.png)

`less /var/log/message
`
![image](https://user-images.githubusercontent.com/38725707/163947663-9ad4b5fd-3ef5-44d8-8e58-4dffe6a9f798.png)

**Comment by ktock** [comment]
> CRI-based authentication 

You need to do the following as well https://github.com/containerd/stargz-snapshotter/blob/v0.11.4/docs/overview.md#cri-based-authentication

> You must specify --image-service-endpoint=unix:///run/containerd-stargz-grpc/containerd-stargz-grpc.sock option to kubelet.

About https://github.com/containerd/stargz-snapshotter/issues/742#issuecomment-1102185315 , the following look like non-estargz images.

> registry.baidubce.com/cce-public/pause:3.1
> registry.baidubce.com/cce-public/cce-cni:v1.3.3

**Comment by ktock** [comment]
@yueyuep Is this still an issue?

**Comment by ktock** [comment]
Feel free to reopen this with additional info if it's still an issue.
