### ISSUE TITLE
Support default path to the configuration file

### ISSUE THREAD

**Issue by ktock** [containerd/stargz-snapshotter#97]
Stargz snapshotter daemon (`containerd-stargz-grpc`) currently doesn't have the default path to the configuration file. So users need to explicitly specify the path using `--config` option.
We should have the default path for the configuration file ([containerd also has the default](https://github.com/containerd/containerd/blob/f13ba8f2f2fd27fc2172453434938170e7807149/docs/man/containerd-config.toml.5.md#synopsis)). `/etc/containerd-stargz-grpc/config.toml` seems good for the default path.

**Comment by ohkinozomu** [comment]
@ktock 
Hi. I've created PR about this. Could you review it?
